### PR TITLE
enable all doors

### PR DESCRIPTION
**Pull request by Niklp09**
Many of these doors are unique and it's nice to have them in a locked and an unlocked variant and I've repaired some recipes

### CODE REVIEW

**Comment by Niklp09** [comment]
Fixed a crash in my_garage_door too (I can remove this commit and submit an extra PR)

**Comment by Niklp09** [comment]
@SmallJoker can you *please* take a look at this?

**Comment by SmallJoker** [comment]
Why are those disabled in the first place? It would be good to know whether there's a reason behind this.

**Comment by Niklp09** [comment]
I have browsed all the commits but could not find any reason. They're disabled since https://github.com/minetest-mods/mydoors/commit/7660c8e5de38f8c2a7c91310d97242f06ad87fb3

**Review by SmallJoker — APPROVED** [review]
Looks good, works. Will merge in a few days unless there's objections.

**Comment by Niklp09** [comment]
@SmallJoker Ping :smile:

**Pull request merged**
